# Generated by Django 4.2.2 on 2023-06-06 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('csvs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('TV', 'tv'), ('IPAD', 'ipad'), ('PLAYSTATION', 'playstation')], max_length=11)),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.FloatField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('saleman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csvs.csv')),
            ],
        ),
    ]
