# Generated by Django 4.2.2 on 2023-06-09 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='saleman',
            new_name='salesman',
        ),
    ]
